char const * => char* conversions fix
Bots-United/metamod-p pull request #21
Opened 2021-08-27 11:28 UTC by p5-vbnekit

fixed compilation on modern compilers - code healing fix for cstr*-str* conversions

2021-11-29 00:47 UTC, TheStormN requested changes

2021-11-29 00:47 UTC, TheStormN commented on metamod/game_support.cpp
> +				strncat(fixname_amd64, "_amd64.so", sizeof(fixname_amd64) - 1);
Why you have modified this piece of code given the intention of the PR?

2021-11-29 08:15 UTC, p5-vbnekit commented on metamod/game_support.cpp
> +				strncat(fixname_amd64, "_amd64.so", sizeof(fixname_amd64) - 1);
Hello!

I hope I understood the question correctly.

# Prologue

https://www.cplusplus.com/reference/cstring/strncpy/

> No null-character is implicitly appended at the end of destination if source is longer than num. Thus, in this case, destination shall not be considered a null terminated C string (reading it as such would overflow).

I know about fixname_amd64 is `char array[NAME_MAX]` and NAME_MAX > 10 (length of "_amd64.so" + 1 (for zero character)). But this is pointless walking on the edge of a knife in this case, in my opinion.

# Answer

To increase the stablility of the code. To reduce the senseless coherence of the code. This kind of thing removes unnecessary pain from other programmers. They can modify the code in other places, and it will require at least one less hazard to be aware of.

2021-11-29 08:17 UTC, p5-vbnekit commented on metamod/game_support.cpp
> +				strncat(fixname_amd64, "_amd64.so", sizeof(fixname_amd64) - 1);
And I forgot (not sure why) to add one more line
`fixname_amd64[sizeof(fixname_amd64) - 1] = 0`
after `strncat(fixname_amd64, "_amd64.so", sizeof(fixname_amd64) - 1);`

2021-11-29 08:27 UTC, p5-vbnekit commented on metamod/game_support.cpp
> +				strncat(fixname_amd64, "_amd64.so", sizeof(fixname_amd64) - 1);
And I can't remember why this change collected in this particular commit and not in a separate one. =)
I can rebase and split this changes if required.

2021-11-29 17:42 UTC, TheStormN commented on metamod/game_support.cpp
> +				strncat(fixname_amd64, "_amd64.so", sizeof(fixname_amd64) - 1);
Ok, read that documentation again and see if your change is meaningful. :) For now, please remove it from the PR and leave only the const fixes.

2021-11-30 12:27 UTC, p5-vbnekit commented on metamod/game_support.cpp
> +				strncat(fixname_amd64, "_amd64.so", sizeof(fixname_amd64) - 1);
Oh, sorry. ahaha! =) I confused `strncpy` and` strncat`.
I will split my PR, Ok.

2021-11-30 12:48 UTC, p5-vbnekit commented on metamod/game_support.cpp
> +				strncat(fixname_amd64, "_amd64.so", sizeof(fixname_amd64) - 1);
But IMHO, this code is still dangerous!!! And I think we have to fix it. =)

Should i open new Issue for it?

# NAME_MAX

Combination of this macro and static char arrays (string buffers) are confusing me (only me?).
Because buffer size should be greater than real name length - terminating null-character are required
`static char fixname_amd64[NAME_MAX];` should be replaced to `static char fixname_amd64[NAME_MAX + 1];`

# strncat

1. we have to leave 1 last byte in the buffer for the null terminator (in case the length of the contained string is actually the maximum). I think so.
2. metamod code does not care about already occupied buffer space, but it's bad behavior.

I consider this code dangerous because the following situations are possible:
1. `fixname_amd64` will not be null terminated (if remaining buffer space is equal to the original length without a null character) - we can get undefined behavior later when reading `fixname_amd64` as a null string.
2. `fixname_amd64` may overflow and we will damage the stack, which will again lead to undefined behavior.

For fix it - `strncat(fixname_amd64, "_amd64.so", sizeof(fixname_amd64))` should be replaced to something like:
```c++
{
    constexpr static char const suffix[] = "_amd64.so";
    auto const left = sizeof(fixname_amd64) - ::strlen(fixname_amd64);
    if (! (left >= sizeof(suffix))) {
        // return overflow error here
    }
    ::strncat(fixname_amd64, "_amd64.so", left);
}
```

# Example of correct code
```c++
#include <cstring>
#include <iostream>
#include <algorithm>

int main(int, char **) {
    static char fixname_amd64[11]; // 1 for `X` + 9 for `_amd64.so` + 1 for null-terminator = 11
    ::std::fill(fixname_amd64, fixname_amd64 + sizeof(fixname_amd64), static_cast<char>(0));
    fixname_amd64[0] = 'X';

    {
      constexpr static char const suffix[] = "_amd64.so";
      auto const left = sizeof(fixname_amd64) - ::strlen(fixname_amd64);
      if (! (left >= sizeof(suffix))) {
        ::std::cerr << "BUFFER OVERFLOW ERROR!" << ::std::endl << ::std::flush;
        return 1;
      }
      ::strncat(fixname_amd64, suffix, left);
    }
    
    ::std::cout << fixname_amd64 << " - " << ::strlen(fixname_amd64) << ::std::endl << ::std::flush;

    return 0;
}
```

# Demonstration of hazards.

```c++
#include <cstring>
#include <iostream>
#include <algorithm>

int main(int, char **) {
    static char safe_buffer[5] = "";
    ::std::fill(safe_buffer, safe_buffer + sizeof(safe_buffer), static_cast<char>(0));
    *safe_buffer = 'X';

    constexpr static auto const fixname_amd64_size = sizeof(safe_buffer) - 2;
    static auto * const fixname_amd64 = safe_buffer;

    ::std::cout << "fixname_amd64 [before]: " << fixname_amd64 << ::std::endl << ::std::flush;

    ::strncat(fixname_amd64, "012", fixname_amd64_size);
    ::std::cout << "fixname_amd64 [after]: " << fixname_amd64 << ::std::endl << ::std::flush;
    
    if (0 != fixname_amd64[fixname_amd64_size - 1]) {
        ::std::cerr << "fixname_amd64 overflow! fixname_amd64[fixname_amd64_size-1] should be zero." << ::std::endl << ::std::flush;
        return 1;
    }

    return 0;
}
```

```c++
#include <cstring>
#include <iostream>
#include <algorithm>

int main(int, char **) {
    static char fixname_amd64[2] = "";
    ::std::fill(fixname_amd64, fixname_amd64 + sizeof(fixname_amd64), static_cast<char>(0));

    ::strncat(fixname_amd64, "01", sizeof(fixname_amd64));
    if (0 != fixname_amd64[sizeof(fixname_amd64) - 1]) {
        ::std::cerr << "fixname_amd64 overflow! fixname_amd64[sizeof(fixname_amd64)-1] should be zero." << ::std::endl << ::std::flush;
        return 1;
    }

    return 0;
}
```

2021-11-30 13:35 UTC, closed without merging

2021-11-30 14:45 UTC, TheStormN commented on metamod/game_support.cpp
> +				strncat(fixname_amd64, "_amd64.so", sizeof(fixname_amd64) - 1);
You give quite some explanations. :) I'm well aware that code as currently is, is far from perfect, no need to give me evidences. Just mind your fixes and keep them in separate PRs. :)